### ISSUE TITLE
EPIC MVP

### ISSUE THREAD

**Issue by GunnarJohansson** [simonsimme/OOProject#17]
**CLIENT**
- [x] Send/receive messages in channel
- [x] Join / Leave Channel

**UI**
- [x] Connect / Disconnect from server
- [x] Join / Leave channel
- [x] Send / Receive messages in channel

**SERVER**
- [x] Start / Stop server
- [x] Join / Leave channel
- [x] Send / Receive messages from users in channel
- [x] Authenticate channel passwords

**APPLICATION**
- [x] Deployable Client Application
- [x] Deployable Server Application
